// demoData.js — Seed/fallback data used when Firestore has no stores yet.
// This guarantees the UI renders meaningful content for development, demos and SEO.
// Once real partners add stores, Firestore data takes priority automatically.

export const DEMO_STORES = [
  {
    id: 'demo-biryani-house',
    slug: 'dhaka-biryani-house',
    name: { en: 'Dhaka Biryani House', bn: 'ঢাকা বিরিয়ানি হাউস' },
    description: {
      en: 'Authentic Kacchi & Tehari delivered hot to your door in Dhanmondi.',
      bn: 'ধানমন্ডিতে গরম গরম কাচ্চি ও তেহারি ডেলিভারি।',
    },
    category: 'restaurant',
    subcategories: ['biryani', 'kacchi', 'bengali'],
    logo: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=200&q=70',
    banner: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=70',
    address: { en: 'Road 27, Dhanmondi', bn: 'রোড ২৭, ধানমন্ডি' },
    district: 'Dhaka', upazila: 'Dhanmondi', division: 'Dhaka',
    lat: 23.7461, lng: 90.3742,
    deliveryRadius: 8, allBangladeshDelivery: false,
    phone: '+8801700000001', whatsapp: '+8801700000001',
    hours: {
      monday: { open: '11:00', close: '23:00', isOpen: true },
      tuesday: { open: '11:00', close: '23:00', isOpen: true },
      wednesday: { open: '11:00', close: '23:00', isOpen: true },
      thursday: { open: '11:00', close: '23:00', isOpen: true },
      friday: { open: '14:00', close: '23:30', isOpen: true },
      saturday: { open: '11:00', close: '23:30', isOpen: true },
      sunday: { open: '11:00', close: '23:00', isOpen: true },
    },
    isOpen: true, isAcceptingOrders: true, isVerified: true, isFeatured: true,
    totalOrders: 1240, recentOrders: 38, averageRating: 4.7, totalRatings: 312,
    profileCompleteness: 95, avgResponseMinutes: 8, deliveryFee: 40, minOrder: 150,
    deliveryTime: 35,
  },
  {
    id: 'demo-fresh-grocery',
    slug: 'fresh-mart-grocery',
    name: { en: 'Fresh Mart Grocery', bn: 'ফ্রেশ মার্ট মুদি' },
    description: {
      en: 'Daily groceries, fresh vegetables and household essentials near Mirpur.',
      bn: 'মিরপুরে প্রতিদিনের মুদি, তাজা সবজি ও নিত্যপ্রয়োজনীয় পণ্য।',
    },
    category: 'grocery', subcategories: ['vegetables', 'daily'],
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&q=70',
    banner: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=70',
    address: { en: 'Section 6, Mirpur', bn: 'সেকশন ৬, মিরপুর' },
    district: 'Dhaka', upazila: 'Mirpur', division: 'Dhaka',
    lat: 23.8069, lng: 90.3687,
    deliveryRadius: 10, allBangladeshDelivery: false,
    phone: '+8801700000002', whatsapp: '+8801700000002',
    hours: {
      monday: { open: '08:00', close: '22:00', isOpen: true },
      tuesday: { open: '08:00', close: '22:00', isOpen: true },
      wednesday: { open: '08:00', close: '22:00', isOpen: true },
      thursday: { open: '08:00', close: '22:00', isOpen: true },
      friday: { open: '08:00', close: '22:00', isOpen: true },
      saturday: { open: '08:00', close: '22:00', isOpen: true },
      sunday: { open: '08:00', close: '22:00', isOpen: true },
    },
    isOpen: true, isAcceptingOrders: true, isVerified: true, isFeatured: false,
    totalOrders: 860, recentOrders: 25, averageRating: 4.5, totalRatings: 198,
    profileCompleteness: 88, avgResponseMinutes: 12, deliveryFee: 30, minOrder: 200,
    deliveryTime: 45,
  },
  {
    id: 'demo-care-pharmacy',
    slug: 'care-plus-pharmacy',
    name: { en: 'Care Plus Pharmacy', bn: 'কেয়ার প্লাস ফার্মেসি' },
    description: {
      en: 'Genuine medicines, healthcare products and 24/7 delivery in Uttara.',
      bn: 'উত্তরায় আসল ওষুধ ও স্বাস্থ্যসেবা পণ্যের ২৪/৭ ডেলিভারি।',
    },
    category: 'pharmacy', subcategories: ['medicine', 'healthcare'],
    logo: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=200&q=70',
    banner: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=70',
    address: { en: 'Sector 7, Uttara', bn: 'সেক্টর ৭, উত্তরা' },
    district: 'Dhaka', upazila: 'Uttara', division: 'Dhaka',
    lat: 23.8759, lng: 90.3795,
    deliveryRadius: 12, allBangladeshDelivery: false,
    phone: '+8801700000003', whatsapp: '+8801700000003',
    hours: {
      monday: { open: '00:00', close: '23:59', isOpen: true },
      tuesday: { open: '00:00', close: '23:59', isOpen: true },
      wednesday: { open: '00:00', close: '23:59', isOpen: true },
      thursday: { open: '00:00', close: '23:59', isOpen: true },
      friday: { open: '00:00', close: '23:59', isOpen: true },
      saturday: { open: '00:00', close: '23:59', isOpen: true },
      sunday: { open: '00:00', close: '23:59', isOpen: true },
    },
    isOpen: true, isAcceptingOrders: true, isVerified: true, isFeatured: true,
    totalOrders: 2100, recentOrders: 64, averageRating: 4.8, totalRatings: 540,
    profileCompleteness: 100, avgResponseMinutes: 5, deliveryFee: 25, minOrder: 100,
    deliveryTime: 30,
  },
  {
    id: 'demo-trendy-threads',
    slug: 'trendy-threads-clothing',
    name: { en: 'Trendy Threads', bn: 'ট্রেন্ডি থ্রেডস' },
    description: {
      en: 'Latest fashion, panjabi, sarees and casual wear with cash on delivery.',
      bn: 'সর্বশেষ ফ্যাশন, পাঞ্জাবি, শাড়ি ও ক্যাজুয়াল পোশাক — ক্যাশ অন ডেলিভারি।',
    },
    category: 'clothing', subcategories: ['fashion', 'panjabi', 'saree'],
    logo: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=200&q=70',
    banner: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=70',
    address: { en: 'New Market', bn: 'নিউ মার্কেট' },
    district: 'Chattogram', upazila: 'Kotwali', division: 'Chattogram',
    lat: 22.3384, lng: 91.8317,
    deliveryRadius: 15, allBangladeshDelivery: true,
    phone: '+8801700000004', whatsapp: '+8801700000004',
    hours: {
      monday: { open: '10:00', close: '21:00', isOpen: true },
      tuesday: { open: '10:00', close: '21:00', isOpen: true },
      wednesday: { open: '10:00', close: '21:00', isOpen: true },
      thursday: { open: '10:00', close: '21:00', isOpen: true },
      friday: { open: '15:00', close: '21:00', isOpen: true },
      saturday: { open: '10:00', close: '21:00', isOpen: true },
      sunday: { open: '10:00', close: '21:00', isOpen: false },
    },
    isOpen: true, isAcceptingOrders: true, isVerified: false, isFeatured: false,
    totalOrders: 430, recentOrders: 12, averageRating: 4.3, totalRatings: 96,
    profileCompleteness: 75, avgResponseMinutes: 20, deliveryFee: 60, minOrder: 500,
    deliveryTime: 60,
  },
  {
    id: 'demo-gadget-zone',
    slug: 'gadget-zone-electronics',
    name: { en: 'Gadget Zone', bn: 'গ্যাজেট জোন' },
    description: {
      en: 'Smartphones, accessories and electronics with warranty and COD.',
      bn: 'স্মার্টফোন, এক্সেসরিজ ও ইলেকট্রনিক্স — ওয়ারেন্টি ও ক্যাশ অন ডেলিভারি।',
    },
    category: 'electronics', subcategories: ['mobile', 'accessories'],
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&q=70',
    banner: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&q=70',
    address: { en: 'Zindabazar', bn: 'জিন্দাবাজার' },
    district: 'Sylhet', upazila: 'Sylhet Sadar', division: 'Sylhet',
    lat: 24.8949, lng: 91.8687,
    deliveryRadius: 20, allBangladeshDelivery: true,
    phone: '+8801700000005', whatsapp: '+8801700000005',
    hours: {
      monday: { open: '10:00', close: '20:00', isOpen: true },
      tuesday: { open: '10:00', close: '20:00', isOpen: true },
      wednesday: { open: '10:00', close: '20:00', isOpen: true },
      thursday: { open: '10:00', close: '20:00', isOpen: true },
      friday: { open: '15:00', close: '20:00', isOpen: true },
      saturday: { open: '10:00', close: '20:00', isOpen: true },
      sunday: { open: '10:00', close: '20:00', isOpen: true },
    },
    isOpen: false, isAcceptingOrders: false, isVerified: true, isFeatured: true,
    totalOrders: 690, recentOrders: 18, averageRating: 4.6, totalRatings: 154,
    profileCompleteness: 90, avgResponseMinutes: 15, deliveryFee: 80, minOrder: 1000,
    deliveryTime: 90,
  },
  {
    id: 'demo-sweet-crumbs',
    slug: 'sweet-crumbs-bakery',
    name: { en: 'Sweet Crumbs Bakery', bn: 'সুইট ক্রাম্বস বেকারি' },
    description: {
      en: 'Fresh cakes, pastries and breads baked daily. Custom cakes available.',
      bn: 'প্রতিদিন তৈরি তাজা কেক, পেস্ট্রি ও রুটি। কাস্টম কেক পাওয়া যায়।',
    },
    category: 'bakery', subcategories: ['cake', 'pastry'],
    logo: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=200&q=70',
    banner: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=70',
    address: { en: 'GEC Circle', bn: 'জিইসি মোড়' },
    district: 'Chattogram', upazila: 'Panchlaish', division: 'Chattogram',
    lat: 22.3590, lng: 91.8214,
    deliveryRadius: 10, allBangladeshDelivery: false,
    phone: '+8801700000006', whatsapp: '+8801700000006',
    hours: {
      monday: { open: '09:00', close: '22:00', isOpen: true },
      tuesday: { open: '09:00', close: '22:00', isOpen: true },
      wednesday: { open: '09:00', close: '22:00', isOpen: true },
      thursday: { open: '09:00', close: '22:00', isOpen: true },
      friday: { open: '09:00', close: '22:00', isOpen: true },
      saturday: { open: '09:00', close: '22:00', isOpen: true },
      sunday: { open: '09:00', close: '22:00', isOpen: true },
    },
    isOpen: true, isAcceptingOrders: true, isVerified: true, isFeatured: false,
    totalOrders: 520, recentOrders: 22, averageRating: 4.9, totalRatings: 210,
    profileCompleteness: 92, avgResponseMinutes: 10, deliveryFee: 50, minOrder: 250,
    deliveryTime: 50,
  },
]

// Demo menu items keyed by store id.
export const DEMO_ITEMS = {
  'demo-biryani-house': [
    { id: 'i-kacchi', slug: 'mutton-kacchi-biryani', storeId: 'demo-biryani-house', categoryId: 'c-main',
      name: { en: 'Mutton Kacchi Biryani', bn: 'মাটন কাচ্চি বিরিয়ানি' },
      description: { en: 'Slow-cooked mutton with aromatic basmati rice.', bn: 'সুগন্ধি বাসমতি চালে রান্না করা মাটন।' },
      price: 320, discountPrice: 280, image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=70',
      isAvailable: true, isFeatured: true, isBestseller: true, totalOrders: 540, averageRating: 4.8, totalRatings: 120, recentViews: 80 },
    { id: 'i-tehari', slug: 'beef-tehari', storeId: 'demo-biryani-house', categoryId: 'c-main',
      name: { en: 'Beef Tehari', bn: 'বিফ তেহারি' },
      description: { en: 'Classic Dhaka-style spicy beef tehari.', bn: 'ঢাকাইয়া ঝাল বিফ তেহারি।' },
      price: 200, discountPrice: 0, image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=70',
      isAvailable: true, isFeatured: false, isBestseller: true, totalOrders: 410, averageRating: 4.6, totalRatings: 95, recentViews: 60 },
    { id: 'i-borhani', slug: 'borhani-glass', storeId: 'demo-biryani-house', categoryId: 'c-drinks',
      name: { en: 'Borhani', bn: 'বোরহানি' },
      description: { en: 'Refreshing spiced yogurt drink.', bn: 'সতেজ মসলাদার দইয়ের পানীয়।' },
      price: 60, discountPrice: 0, image: 'https://images.unsplash.com/photo-1626078299034-94f0d6b8c6db?w=400&q=70',
      isAvailable: true, isFeatured: false, isBestseller: false, totalOrders: 220, averageRating: 4.4, totalRatings: 50, recentViews: 30 },
  ],
  'demo-fresh-grocery': [
    { id: 'g-rice', slug: 'miniket-rice-5kg', storeId: 'demo-fresh-grocery', categoryId: 'c-staples',
      name: { en: 'Miniket Rice 5kg', bn: 'মিনিকেট চাল ৫ কেজি' },
      description: { en: 'Premium quality miniket rice.', bn: 'প্রিমিয়াম মানের মিনিকেট চাল।' },
      price: 380, discountPrice: 350, image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=70',
      isAvailable: true, isFeatured: true, isBestseller: true, totalOrders: 300, averageRating: 4.5, totalRatings: 70, recentViews: 40 },
    { id: 'g-egg', slug: 'farm-eggs-dozen', storeId: 'demo-fresh-grocery', categoryId: 'c-staples',
      name: { en: 'Farm Eggs (Dozen)', bn: 'ফার্মের ডিম (ডজন)' },
      description: { en: 'Fresh farm eggs, 12 pcs.', bn: 'তাজা ফার্মের ডিম, ১২টি।' },
      price: 140, discountPrice: 0, image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&q=70',
      isAvailable: true, isFeatured: false, isBestseller: true, totalOrders: 260, averageRating: 4.6, totalRatings: 55, recentViews: 35 },
  ],
  'demo-care-pharmacy': [
    { id: 'p-napa', slug: 'napa-500mg', storeId: 'demo-care-pharmacy', categoryId: 'c-meds',
      name: { en: 'Napa 500mg (Strip)', bn: 'নাপা ৫০০মিগ্রা (পাতা)' },
      description: { en: 'Paracetamol tablets, 10 pcs.', bn: 'প্যারাসিটামল ট্যাবলেট, ১০টি।' },
      price: 25, discountPrice: 0, image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&q=70',
      isAvailable: true, isFeatured: true, isBestseller: true, totalOrders: 900, averageRating: 4.9, totalRatings: 300, recentViews: 120 },
    { id: 'p-mask', slug: 'surgical-mask-box', storeId: 'demo-care-pharmacy', categoryId: 'c-health',
      name: { en: 'Surgical Mask (Box of 50)', bn: 'সার্জিক্যাল মাস্ক (৫০টি)' },
      description: { en: '3-ply disposable masks.', bn: '৩-প্লাই ডিসপোজেবল মাস্ক।' },
      price: 180, discountPrice: 150, image: 'https://images.unsplash.com/photo-1584634731339-252c581abfc5?w=400&q=70',
      isAvailable: true, isFeatured: false, isBestseller: false, totalOrders: 400, averageRating: 4.7, totalRatings: 110, recentViews: 50 },
  ],
}

// Demo menu categories per store (used by store page grouping).
export const DEMO_MENU_CATEGORIES = {
  'demo-biryani-house': [
    { id: 'c-main', name: { en: 'Main Dishes', bn: 'প্রধান খাবার' }, order: 1 },
    { id: 'c-drinks', name: { en: 'Drinks', bn: 'পানীয়' }, order: 2 },
  ],
  'demo-fresh-grocery': [
    { id: 'c-staples', name: { en: 'Staples', bn: 'নিত্যপণ্য' }, order: 1 },
  ],
  'demo-care-pharmacy': [
    { id: 'c-meds', name: { en: 'Medicines', bn: 'ওষুধ' }, order: 1 },
    { id: 'c-health', name: { en: 'Healthcare', bn: 'স্বাস্থ্যসেবা' }, order: 2 },
  ],
}
